#DROP DATABASE SBX_W;

CREATE DATABASE IF NOT EXISTS SBX_W;

USE SBX_W;

CREATE TABLE IF NOT EXISTS TBL_TIPO_IDENTIFICACION(
Id INT NOT NULL AUTO_INCREMENT,
Nombre VARCHAR(50),
Descripcion VARCHAR(200),
PRIMARY KEY(Id)
);

INSERT INTO TBL_TIPO_IDENTIFICACION (Nombre,Descripcion)
VALUES('CC','Cedula'),('TI','Tarjeta de identidad'),('CE','Cedula extranjera');

CREATE TABLE IF NOT EXISTS TBL_PAIS(
Id INT NOT NULL AUTO_INCREMENT,
Codigo INT,
Nombre VARCHAR(50),
PRIMARY KEY(Id)
);

INSERT INTO TBL_PAIS(Codigo,Nombre) 
VALUES(1,'Colombia'),(2,'Venezuela');

CREATE TABLE IF NOT EXISTS TBL_DEPARTAMENTO(
Id INT NOT NULL AUTO_INCREMENT,
Codigo INT,
Nombre VARCHAR(50),
PRIMARY KEY(Id)
);

INSERT INTO TBL_DEPARTAMENTO(Codigo,Nombre) 
VALUES(1,'Valle del cauca');

CREATE TABLE IF NOT EXISTS TBL_CIUDAD(
Id INT NOT NULL AUTO_INCREMENT,
Codigo INT,
Nombre VARCHAR(50),
PRIMARY KEY(Id)
);

INSERT INTO TBL_CIUDAD(Codigo,Nombre) 
VALUES(1,'Cali'),(2,'Poblado campestre'),(3,'Villagorgona'),(4,'Candelaria'),(5,'Carmelo');

CREATE TABLE IF NOT EXISTS TBL_COMPANIA (
Id INT NOT NULL AUTO_INCREMENT,
Id_Tipo_identificacion int,
Identificacion VARCHAR(20),
Nombre VARCHAR(100),
Telefono VARCHAR(10),
Celular VARCHAR(12),
Email VARCHAR(100),
Direccion VARCHAR(100),
Id_ciudad INT,
Id_departamento INT,
Id_pais INT,
PRIMARY KEY(Id),
FOREIGN KEY(Id_Tipo_identificacion) REFERENCES TBL_TIPO_IDENTIFICACION(Id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(Id_ciudad) REFERENCES TBL_CIUDAD(Id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(Id_departamento) REFERENCES TBL_DEPARTAMENTO(Id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(Id_pais) REFERENCES TBL_PAIS(Id) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO TBL_COMPANIA(Id_Tipo_identificacion,Identificacion,Nombre,Telefono,Celular,Email,Direccion,Id_ciudad,Id_departamento,Id_pais) 
VALUES(1,'1','NA','0','0','','',3,1,1);

CREATE TABLE IF NOT EXISTS TBL_PERSONA(
Id INT NOT NULL AUTO_INCREMENT,
Id_Tipo_identificacion int,
Identificacion VARCHAR(20),
Nombres VARCHAR(100),
Apellidos VARCHAR(100),
FechaNacimiento DATE,
Celular VARCHAR(12),
Email VARCHAR(100),
Direccion VARCHAR(100),
Id_ciudad INT,
Id_departamento INT,
Id_pais INT,
PRIMARY KEY(Id),
FOREIGN KEY(Id_Tipo_identificacion) REFERENCES TBL_TIPO_IDENTIFICACION(Id),
FOREIGN KEY(Id_ciudad) REFERENCES TBL_CIUDAD(Id),
FOREIGN KEY(Id_departamento) REFERENCES TBL_DEPARTAMENTO(Id),
FOREIGN KEY(Id_pais) REFERENCES TBL_PAIS(Id)
);

INSERT INTO TBL_PERSONA (Id_Tipo_identificacion,Identificacion,Nombres,Apellidos,FechaNacimiento,Celular,Email,Direccion,Id_ciudad,Id_departamento,Id_pais)
VALUES(1,'1','Na','Na','2024-01-08','0','','',3,1,1);

CREATE TABLE IF NOT EXISTS TBL_ESTADO(
Id INT NOT NULL AUTO_INCREMENT,
Nombre VARCHAR(100),
PRIMARY KEY(Id)
);

INSERT INTO TBL_ESTADO (Nombre)
VALUES('Activo'),('Inactivo');

CREATE TABLE IF NOT EXISTS TBL_ROL(
Id INT NOT NULL AUTO_INCREMENT,
Nombre VARCHAR(100),
PRIMARY KEY(Id)
);

INSERT INTO TBL_ROL (Nombre)
VALUES('Admin'),('Cobrador');

CREATE TABLE IF NOT EXISTS TBL_MODULO(
Id INT NOT NULL AUTO_INCREMENT,
Nombre VARCHAR(100),
PRIMARY KEY(Id)
);

INSERT INTO TBL_MODULO (Nombre)
VALUES('Clientes'),('Configuracion'),('Cartera'),('Abonos');

CREATE TABLE IF NOT EXISTS TBL_PERMISO(
Id INT NOT NULL AUTO_INCREMENT,
Nombre VARCHAR(100),
PRIMARY KEY(Id)
);

INSERT INTO TBL_PERMISO (Nombre)
VALUES('Leer'),('Actualizar'),('Crear'),('Eliminar');

CREATE TABLE IF NOT EXISTS TBL_MODULO_PERMISO(
Id INT NOT NULL AUTO_INCREMENT,
Id_modulo INT,
Id_permiso INT,
PRIMARY KEY(Id),
FOREIGN KEY(Id_modulo) REFERENCES TBL_MODULO(Id),
FOREIGN KEY(Id_permiso) REFERENCES TBL_PERMISO(Id)
);

INSERT INTO TBL_MODULO_PERMISO(Id_modulo,Id_permiso) 
VALUES
(1,1),(1,2),(1,3),(1,4),
(2,1),(2,2),(2,3),(2,4),
(3,1),(3,2),(3,3),(4,4),
(4,1),(4,2),(4,3),(4,4);

CREATE TABLE IF NOT EXISTS TBL_MODULO_PERMISO_ROL(
Id INT NOT NULL AUTO_INCREMENT,
Id_modulo_permiso INT,
Id_rol INT,
PRIMARY KEY(Id),
FOREIGN KEY(Id_modulo_permiso) REFERENCES TBL_MODULO_PERMISO(Id),
FOREIGN KEY(Id_rol) REFERENCES TBL_ROL(Id)
);

INSERT INTO TBL_MODULO_PERMISO_ROL (Id_modulo_permiso,Id_rol) 
VALUES
(1,1),
(2,1),
(3,1),
(4,1);

CREATE TABLE IF NOT EXISTS TBL_USUARIO(
Id INT NOT NULL AUTO_INCREMENT,
Usuario VARCHAR(50),
Contrasena VARCHAR(300),
Id_persona INT,
Id_rol INT,
PRIMARY KEY(Id),
FOREIGN KEY(Id_persona) REFERENCES TBL_PERSONA(Id),
FOREIGN KEY(Id_rol) REFERENCES TBL_ROL(Id)
);

INSERT INTO TBL_USUARIO (Usuario,Contrasena,Id_persona,Id_rol)
VALUES ('admin','admin',1,1);

CREATE TABLE IF NOT EXISTS TBL_CLIENTE(
Id INT NOT NULL AUTO_INCREMENT,
Id_persona INT,
Id_estado INT,
Fecha_registro DATETIME,
PRIMARY KEY(Id),
FOREIGN KEY(Id_persona) REFERENCES TBL_PERSONA(Id),
FOREIGN KEY(Id_estado) REFERENCES TBL_ESTADO(Id)
);

CREATE TABLE IF NOT EXISTS TBL_PERIODICIDAD_PAGO(
Id INT NOT NULL AUTO_INCREMENT,
Nombre VARCHAR(100),
PRIMARY KEY(Id)
);

INSERT INTO TBL_PERIODICIDAD_PAGO (Nombre) VALUES('Diario'),('Semanal'),('Quincenal'),('Mensual'),('Trimestral'),('Semestral'),('Anual');

CREATE TABLE IF NOT EXISTS TBL_CUENTAS_POR_COBRAR(
Id INT NOT NULL AUTO_INCREMENT,
Numero_factura VARCHAR(100),
Id_cliente INT,
FechaInicio DATE,
FechaFin DATE,
Valor DECIMAL,
Id_periodicidad_pago INT,
Fecha_registro DATETIME,
PRIMARY KEY(Id),
FOREIGN KEY(Id_cliente) REFERENCES TBL_CLIENTE(Id),
FOREIGN KEY(Id_periodicidad_pago) REFERENCES TBL_PERIODICIDAD_PAGO(Id)
);

CREATE TABLE IF NOT EXISTS TBL_ABONOS(
Id INT NOT NULL AUTO_INCREMENT,
Id_cuenta_cobro INT,
Valor DECIMAL,
Fecha_registro DATETIME,
PRIMARY KEY(Id),
FOREIGN KEY(Id_cuenta_cobro) REFERENCES TBL_CUENTAS_POR_COBRAR(Id)
);



